### ISSUE TITLE
Debug mode compile caused linking issue

### ISSUE THREAD

**Issue by ZiXuanVickyLu** [shg8/3DGS.cpp#14]
Thanks for this good project! I have to say that I have successfully run the project with my data on Release Mode:
![image](https://github.com/shg8/VulkanSplatting/assets/53465084/bb681707-f15f-434c-84ed-0d77f709c3b3)
 But on Windows platform with (MSVC 2022 buildtool), the Debug mode will cause the linking issue:
![image](https://github.com/shg8/VulkanSplatting/assets/53465084/cddb3485-dbf5-4d25-99ca-97cb2a5a9108)
which is quite strange. Any suggestion?
On the other hands, the profiler sames not meet the diagram size (I guess?), because the diagrams crowed on the right side:
![image](https://github.com/shg8/VulkanSplatting/assets/53465084/e447f50e-85dd-4330-9f90-7bc940095040)
(This data is of a black background, don't worry about the result displayed)

Any suggestion about that?

Anyway, this is just a little "bug" I have encountered, so I would like to share and report it. 
Thanks for the contribution of such a great project :-). Best!

**Comment by shg8** [comment]
Thanks for raising the issue! Both problems should be fixed with the latest commit on `main`.

**Comment by shg8** [comment]
Closing this for now. Feel free to reopen if the issues persist.

**Comment by ZiXuanVickyLu** [comment]
Thanks for the reply! :-)
