### ISSUE TITLE
Question  about sort.comp

### ISSUE THREAD

**Issue by xiaoyaoing** [shg8/3DGS.cpp#21]
Hello, this is a really great job for me! But I'm having trouble reading the source code, can you explain it to me? I think sort.comp needs to be sorted according to depth, but I didn’t find the part that uses depth sorting. I only saw the code that groups the tiles together in one tile. Can you help me answer it? Thank you very much.

**Comment by shg8** [comment]
Of course. We sort key value pairs where the key is (tile_id << 32 | depth) and the value is the index of the Gaussian. The [tile_boundary](https://github.com/shg8/3DGS.cpp/blob/main/src/shaders/tile_boundary.comp) shader then calculates the boundaries between each tile. Then, the [render](https://github.com/shg8/3DGS.cpp/blob/main/src/shaders/render.comp) shader is launched with a 16x16 tile size. The boundaries are used for each tile to iterate through the instances sorted by depth in that tile.

**Comment by xiaoyaoing** [comment]
Thank you so much for your prompt and helpful response!  I understand it now. Wish you all the best!
