### ISSUE TITLE
rename the executable file on windows with 'vviewer.exe'

### ISSUE THREAD

**Issue by gyh8** [shg8/3DGS.cpp#24]
I suggest to rename the executable file on windows as 'vviewer.exe'. So it can be run without changing anything. Vviewer sounds a nice name for a Vulkan viewer.

**Comment by shg8** [comment]
Thanks for the suggestion. The viewer with the name as is should be able to run without problems. What were the issues that you've encountered? That being said, I renamed the generated binaries to "3dgs_viewer".
