### ISSUE TITLE
Rendering red screen

### ISSUE THREAD

**Issue by alexthegoodman** [shg8/3DGS.cpp#26]
Good afternoon! Thank you for the amazing 3DGS.cpp project. I have some background with WebGPU and basic TensorFlow but am generally still learning graphics programming and machine learning concepts.

I have an issue that may be related to my incorrect usage or settings, so my apologies ahead of time. However, the issue is pictured below:

![image](https://github.com/shg8/3DGS.cpp/assets/746071/952e6b70-13a6-488e-ab89-79ba0ecff1b9)

I tried the nightly build as well 3 different builds at various stages in the commit history, but the latest seems most stable. Yet it is only giving a red screen.

I am able to open schoolbus.ply in another Python-based viewer. The file is binary (text header, binary body) as required.

I have a fresh installation of Vulkan and all the needed dependencies, and I am able to run Vulkan Cube, so it seems that Vulkan is working properly. If you'd like to examine schoolbus.ply, I could probably ask my client if that is okay!

Thank you for your time!

**Comment by shg8** [comment]
Hi, thanks for raising the issue. Were you able to open other ply files with the latest version? What about with previous commits? If [this line](https://github.com/shg8/3DGS.cpp/blob/dc698675011dd6bec999a961ab2f6556d21fe47e/src/shaders/render.comp#L97) remains commented, I can't think of what might have caused this.

**Comment by alexthegoodman** [comment]
@shg8 I wound up being able to open a flowers model from the "official link" mentioned here: https://github.com/limacv/GaussianSplattingViewer/tree/main?tab=readme-ov-file#usage

I will look into getting the ply file(s) we have. Thanks!

**Comment by ManishJu** [comment]
I am getting the same issue on my Mac with the bicycle scene :

https://github.com/shg8/3DGS.cpp/assets/24234466/ea6a9fe5-8928-48fd-8a60-84b5c24660c1

**Comment by ManishJu** [comment]
I got it working on the files in the point cloud folder. those were actually trained on the sfm data , I was previously trying with the input file . Here is the result : 

https://github.com/shg8/3DGS.cpp/assets/24234466/71622883-429b-4422-84da-44d5043486db
