### ISSUE TITLE
missing head file shaders.h in GSScene.cpp

### ISSUE THREAD

**Issue by moonChen2** [shg8/3DGS.cpp#31]
I run the program on apple m1 pro with next command line and run successfully:
mkdir build
cd build
cmake ..
make 
cd build/apps/viewer
./3dgs_viewer ply_file_path

but when I want to check the code i found there is an error My CLion told me:
![image](https://github.com/shg8/3DGS.cpp/assets/139872598/c8b636fc-31d7-4e0e-a141-93615ef3c0da)

**Comment by shg8** [comment]
There are certain headers that are generated by CMake. Please make sure it's configured correctly in your IDE.
