### ISSUE TITLE
VULKAN_HPP_TYPESAFE_CONVERSION not defined on linux installation

### ISSUE THREAD

**Issue by Six-Bit-007** [shg8/3DGS.cpp#32]
![image](https://github.com/user-attachments/assets/04302970-050d-406f-bb99-8e205a506f07)
I have all the dependencies installed though Vulkan SDK. 
However, when running 
```
cmake --build ./build -j4
```
I got the following error
![image](https://github.com/user-attachments/assets/d81b0600-92e4-43bf-8b99-548065ed3a36)

I'm building the project on wsl2.

**Comment by shg8** [comment]
The project hasn't been tested on WSL. Are you able to compiler other Vulkan programs?

Also, I believe Vulkan on WSL2 is via llvmpipe. Please consider using other native toolchains on Windows.

**Comment by niansa** [comment]
I am seeing the same issue on Debian Trixie with radv.
