### ISSUE TITLE
Does not produce correct renderings

### ISSUE THREAD

**Issue by vvhitedog** [shg8/3DGS.cpp#33]
Hi,

I've been experimenting with this tool, and it clearly renders scenes incorrectly when compared with the other tools such as SIBR viewer extension included by the original 3DGS authors. 

In fact, nearly all viewers produce very low quality renderings of the gaussian splattings other than SIBR, or the `render.py` script in the original 3DGS repo, in my testing. 

To see what I mean and fix this issue, it would be good to write unit or integration tests that:

* Take an established trained 3DGS example.
* Input several new camera positions in the `render.py` program supplied by the original 3DGS 
* Verify you match close to if not exactly the quality produced there.
* This should be especially apparent of "far-field" gaussians, but generally true in other areas of low splat density.

As it is, this render gives a very poor impression of the quality of results possible with 3DGS.

**Comment by shg8** [comment]
Could you elaborate on how the rendering is clearly incorrect? Some screenshots or PSNR number would be helpful.
