### ISSUE TITLE
Strange visualization results with some ply file.

### ISSUE THREAD

**Issue by RobotiX101** [shg8/3DGS.cpp#36]
Here is the ply file
[point_cloud.zip](https://github.com/user-attachments/files/17056775/point_cloud.zip)

In open3d, it looks like this

![image](https://github.com/user-attachments/assets/225edab9-8c71-4571-8339-69f6a5f92eb1)

while use 3dgs_viwer:
![image](https://github.com/user-attachments/assets/8d136065-d873-4b51-8d6c-ff1115e552e0)

and it sometimes crashes

**Comment by glibbist** [comment]
The file you posted is missing all of the 2nd and 3rd Spherical Harmonic data.  GSScene.cpp assumes all of that data is there, and each vertex has 62 float properties, in this order:
```
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float f_dc_0
property float f_dc_1
property float f_dc_2
property float f_rest_0
property float f_rest_1
property float f_rest_2
property float f_rest_3
property float f_rest_4
property float f_rest_5
property float f_rest_6
property float f_rest_7
property float f_rest_8
property float f_rest_9
property float f_rest_10
property float f_rest_11
property float f_rest_12
property float f_rest_13
property float f_rest_14
property float f_rest_15
property float f_rest_16
property float f_rest_17
property float f_rest_18
property float f_rest_19
property float f_rest_20
property float f_rest_21
property float f_rest_22
property float f_rest_23
property float f_rest_24
property float f_rest_25
property float f_rest_26
property float f_rest_27
property float f_rest_28
property float f_rest_29
property float f_rest_30
property float f_rest_31
property float f_rest_32
property float f_rest_33
property float f_rest_34
property float f_rest_35
property float f_rest_36
property float f_rest_37
property float f_rest_38
property float f_rest_39
property float f_rest_40
property float f_rest_41
property float f_rest_42
property float f_rest_43
property float f_rest_44
property float opacity
property float scale_0
property float scale_1
property float scale_2
property float rot_0
property float rot_1
property float rot_2
property float rot_3
```

**Comment by shg8** [comment]
> The file you posted is missing all of the 2nd and 3rd Spherical Harmonic data. GSScene.cpp assumes all of that data is there, and each vertex has 62 float properties, in this order:
> 
> ```
> property float x
> property float y
> property float z
> property float nx
> property float ny
> property float nz
> property float f_dc_0
> property float f_dc_1
> property float f_dc_2
> property float f_rest_0
> property float f_rest_1
> property float f_rest_2
> property float f_rest_3
> property float f_rest_4
> property float f_rest_5
> property float f_rest_6
> property float f_rest_7
> property float f_rest_8
> property float f_rest_9
> property float f_rest_10
> property float f_rest_11
> property float f_rest_12
> property float f_rest_13
> property float f_rest_14
> property float f_rest_15
> property float f_rest_16
> property float f_rest_17
> property float f_rest_18
> property float f_rest_19
> property float f_rest_20
> property float f_rest_21
> property float f_rest_22
> property float f_rest_23
> property float f_rest_24
> property float f_rest_25
> property float f_rest_26
> property float f_rest_27
> property float f_rest_28
> property float f_rest_29
> property float f_rest_30
> property float f_rest_31
> property float f_rest_32
> property float f_rest_33
> property float f_rest_34
> property float f_rest_35
> property float f_rest_36
> property float f_rest_37
> property float f_rest_38
> property float f_rest_39
> property float f_rest_40
> property float f_rest_41
> property float f_rest_42
> property float f_rest_43
> property float f_rest_44
> property float opacity
> property float scale_0
> property float scale_1
> property float scale_2
> property float rot_0
> property float rot_1
> property float rot_2
> property float rot_3
> ```

Thanks for the explanation
