### ISSUE TITLE
how to run on windows

### ISSUE THREAD

**Issue by githubnameoo** [shg8/3DGS.cpp#40]

**Comment by shg8** [comment]
Please refer to the instructions in the README

**Comment by githubnameoo** [comment]
E:\app2\vulkan\Include\vulkan/vulkan_hpp_macros.hpp(135,38): fatal error C1017: 无效的整数常量表达式 [D:\0\project\3DGS.cpp-main\
3DGS.cpp-main\build\src\3dgs_cpp.vcxproj]
how to solve it

**Comment by githubnameoo** [comment]
Windows
After installing Vulkan SDK, set the VULKAN_SDK environmental variable to the install path. Alternatively, pass -DVULKAN_SDK=\INSTALL\LOCATION\OF\YOUR\SDK to CMake when configuring.
how to run details

**Comment by githubnameoo** [comment]
can you tell me&nbsp;How to encapsulate as dll so that it can be called in c#，looking for your reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shg8/3DGS.cpp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月8日(星期二) 凌晨3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shg8/3DGS.cpp] how to run on windows (Issue #40)





 
Closed #40 as not planned.

**Comment by shg8** [comment]
I'm not familiar with C++/C# interop so unfortunately I'm unable to help

**Comment by githubnameoo** [comment]
> _No description provided._

how to make dll file
